%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: H:\My Documents\9495co2t.xlsx
%    Worksheet: 9495CO2T
%
% Auto-generated by MATLAB on 26-Apr-2019 11:12:54

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "9495CO2T";
opts.DataRange = "A2:E1974";

% Specify column names and types
opts.VariableNames = ["TRAP_NUM", "MO", "WK", "YR", "CXT"];
opts.SelectedVariableNames = ["TRAP_NUM", "MO", "WK", "YR", "CXT"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
TrapCounts = readtable("H:\My Documents\9495co2t.xlsx", opts, "UseExcel", false);
TrapCounts=TrapCounts(~any(ismissing(TrapCounts),2),:);

%% Clear temporary variables
clear opts

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Lat", "Lon", "TRAP_NUM", "description"];
opts.VariableTypes = ["double", "double", "double", "string"];
opts = setvaropts(opts, 4, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 4, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TrapSites = readtable("\\stuhome.psu.ds.pdx.edu\j\jocole\My Documents\TrapSites.csv", opts);
TrapSites = removevars(TrapSites,{'description'});


%% Clear temporary variables
clear opts

% Coachella Valley Boundaries
minlat = -116.166666667;
minlon =   33.433333333;
maxlat = -115.833333333;
maxlon =   33.566666667;
[XQ,YQ] = meshgrid(linspace(minlat,maxlat,1000),linspace(minlon,maxlon,1000));
mygriddata = @(x,y,c){griddata(x,y,c,XQ,YQ)};

Traps = join(TrapCounts,TrapSites);
Times = findgroups(Traps.YR,Traps.WK);
AbundanceFrames = splitapply(mygriddata,Traps.Lat,Traps.Lon,Traps.CXT,Times);
AbundanceFrames = cat(3, AbundanceFrames{:});
AbundanceFrames(isnan(AbundanceFrames)) = 0;
AbundanceFrames = AbundanceFrames./max(AbundanceFrames(:));

%% Write the video
v = VideoWriter('abundance.avi');
v.FrameRate = 0.5;
open(v);
% Create a set of frames and write each frame to the file.
figure
for k = 1:size(AbundanceFrames,3)
   imagesc(AbundanceFrames(:,:,k));
   frame = getframe;
   writeVideo(v,frame);
end
close(v);